#For tree types: see org.bukkit.TreeType
biomeMap: 'antik3_terrain.png'
heightMap: 'antik3_heightmap.png'
waterHeight: 60
biomes:
  clearing:
    r: 255
    g: 0
    b: 0
    blocks:
      DIRT:
        block: 3
        data: 0
        chance: 0.35
      COARSEDIRT:
        block: 3
        data: 1
        chance: 0.35
      PODSOL:
        block: 3
        data: 2
        chance: 0.1
      GRASS:
        block: 2
        data: 0
        chance: 0.1
      GRAVEL:
        block: 13
        data: 0
        chance: 0.1
    biome: PLAINS
    snow: false
    floraCount: 60
    floraTypes:
      grass:
        block: 31
        data: 1
        chance: 0.5
      farn:
        block: 31
        data: 2
        chance: 0.3
      blue:
        block: 38
        data: 1
        chance: 0.1
      violett:
        block: 38
        data: 2
        chance: 0.1
    treeCount: 1
    treeTypes:
      oak:
        type: TREE
        chance: 0.9
      largeoak:
        type: BIG_TREE
        chance: 0.1
      birch:
        type: BIRCH
        chance: 0.1
    schematicCount: 0
    schematics: null
    veinCount: 15
    veinTypes:
      diamond:
        block: 56
        data: 0
        chance: 0.01
        length: 2
        stroke: 1
      gold:
        block: 14
        data: 0
        chance: 0.03
        length: 2
        stroke: 2
      iron:
        block: 15
        data: 0
        chance: 0.1
        length: 3
        stroke: 2
      coal:
        block: 16
        data: 0
        chance: 0.15
        length: 3
        stroke: 3
      emerald:
        block: 129
        data: 0
        chance: 0.01
        length: 1
        stroke: 0
      lapis:
        block: 21
        data: 0
        chance: 0.03
        length: 2
        stroke: 2
      redstone:
        block: 73
        data: 0
        chance: 0.07
        length: 3
        stroke: 2
      granite:
        block: 1
        data: 1
        chance: 0.1
        length: 3
        stroke: 2
      diorite:
        block: 1
        data: 3
        chance: 0.1
        length: 3
        stroke: 2
      andesite:
        block: 1
        data: 5
        chance: 0.1
        length: 3
        stroke: 2
      dirt:
        block: 3
        data: 0
        chance: 0.3
        length: 5
        stroke: 4
      air:
        block: 0
        data: 0
        chance: 0.5
        length: 12
        stroke: 5
  beach:
    r: 255
    g: 255
    b: 0
    blocks:
      SAND:
        block: 12
        data: 0
        chance: 0.9
      SANDSTONE:
        block: 24
        data: 0
        chance: 0.1
    biome: BEACHES
    snow: false
    floraCount: 0
    floraTypes: null
    treeCount: 0
    treeTypes: null
    schematicCount: 0
    schematics:
      Palm1:
        fileName: 'Palm1.schematic'
        chance: 0.3
      Palm2:
        fileName: 'Palm2.schematic'
        chance: 0.3
      Palm3:
        fileName: 'Palm3.schematic'
        chance: 0.3
      Palm4:
        fileName: 'Palm4.schematic'
        chance: 0.3
      Palm5:
        fileName: 'Palm5.schematic'
        chance: 0.3
    veinCount: 15
    veinTypes:
      diamond:
        block: 56
        data: 0
        chance: 0.01
        length: 2
        stroke: 1
      gold:
        block: 14
        data: 0
        chance: 0.03
        length: 2
        stroke: 2
      iron:
        block: 15
        data: 0
        chance: 0.1
        length: 3
        stroke: 2
      coal:
        block: 16
        data: 0
        chance: 0.15
        length: 3
        stroke: 3
      emerald:
        block: 129
        data: 0
        chance: 0.01
        length: 1
        stroke: 0
      lapis:
        block: 21
        data: 0
        chance: 0.03
        length: 2
        stroke: 2
      redstone:
        block: 73
        data: 0
        chance: 0.07
        length: 3
        stroke: 2
      granite:
        block: 1
        data: 1
        chance: 0.1
        length: 3
        stroke: 2
      diorite:
        block: 1
        data: 3
        chance: 0.1
        length: 3
        stroke: 2
      andesite:
        block: 1
        data: 5
        chance: 0.1
        length: 3
        stroke: 2
      dirt:
        block: 3
        data: 0
        chance: 0.3
        length: 5
        stroke: 4
      air:
        block: 0
        data: 0
        chance: 0.5
        length: 12
        stroke: 5
  forest:
    r: 0
    g: 100
    b: 0
    biome: FOREST
    snow: false
    blocks:
      GRASS:
        block: 2
        data: 0
        chance: 0.9
      COARSEDIRT:
        block: 3
        data: 1
        chance: 0.1
    floraCount: 70
    floraTypes:
      grass:
        block: 31
        data: 1
        chance: 0.7
      farn:
        block: 31
        data: 2
        chance: 0.1
      yellow:
        block: 37
        data: 0
        chance: 0.05
      red:
        block: 38
        data: 0
        chance: 0.05
      white:
        block: 38
        data: 3
        chance: 0.1
    treeCount: 12
    treeTypes:
      oak:
        type: TREE
        chance: 0.9
      largeoak:
        type: BIG_TREE
        chance: 0.1
      birch:
        type: BIRCH
        chance: 0.1
    schematicCount: 0
    schematics: null
    veinCount: 15
    veinTypes:
      diamond:
        block: 56
        data: 0
        chance: 0.01
        length: 2
        stroke: 1
      gold:
        block: 14
        data: 0
        chance: 0.03
        length: 2
        stroke: 2
      iron:
        block: 15
        data: 0
        chance: 0.1
        length: 3
        stroke: 2
      coal:
        block: 16
        data: 0
        chance: 0.15
        length: 3
        stroke: 3
      emerald:
        block: 129
        data: 0
        chance: 0.01
        length: 1
        stroke: 0
      lapis:
        block: 21
        data: 0
        chance: 0.03
        length: 2
        stroke: 2
      redstone:
        block: 73
        data: 0
        chance: 0.07
        length: 3
        stroke: 2
      granite:
        block: 1
        data: 1
        chance: 0.1
        length: 3
        stroke: 2
      diorite:
        block: 1
        data: 3
        chance: 0.1
        length: 3
        stroke: 2
      andesite:
        block: 1
        data: 5
        chance: 0.1
        length: 3
        stroke: 2
      dirt:
        block: 3
        data: 0
        chance: 0.3
        length: 5
        stroke: 4
      air:
        block: 0
        data: 0
        chance: 0.5
        length: 12
        stroke: 5
  mountainstone:
    r: 200
    g: 200
    b: 200
    blocks:
      STONE:
        block: 1
        data: 0
        chance: 0.8
      GRANITE:
        block: 1
        data: 1
        chance: 0.01
      DIORITE:
        block: 1
        data: 3
        chance: 0.01
      ANDESITE:
        block: 1
        data: 5
        chance: 0.01
      COARSEDIRT:
        block: 3
        data: 1
        chance: 0.01
    biome: EXTREME_HILLS
    snow: true
    floraCount: 10
    floraTypes:
      grass:
        block: 31
        data: 1
        chance: 0.8
      farn:
        block: 31
        data: 2
        chance: 0.2
    treeCount: 0
    treeTypes: null
    schematicCount: 0
    schematics: null
    veinCount: 15
    veinTypes:
      diamond:
        block: 56
        data: 0
        chance: 0.02
        length: 2
        stroke: 1
      gold:
        block: 14
        data: 0
        chance: 0.03
        length: 2
        stroke: 2
      emerald:
        block: 129
        data: 0
        chance: 0.01
        length: 1
        stroke: 0
      iron:
        block: 15
        data: 0
        chance: 0.15
        length: 3
        stroke: 2
      coal:
        block: 16
        data: 0
        chance: 0.2
        length: 3
        stroke: 3
      redstone:
        block: 73
        data: 0
        chance: 0.05
        length: 3
        stroke: 2
      granite:
        block: 1
        data: 1
        chance: 0.05
        length: 3
        stroke: 2
      diorite:
        block: 1
        data: 3
        chance: 0.05
        length: 3
        stroke: 2
      andesite:
        block: 1
        data: 5
        chance: 0.05
        length: 3
        stroke: 2
      air:
        block: 0
        data: 0
        chance: 0.3
        length: 10
        stroke: 4
  desert:
    r: 255
    g: 100
    b: 0
    blocks:
      SAND:
        block: 12
        data: 0
        chance: 0.8
      REDSAND:
        block: 12
        data: 1
        chance: 0.1
      SANDSTONE:
        block: 24
        data: 0
        chance: 0.1
    biome: DESERT
    snow: false
    floraCount: 4
    floraTypes:
      deadshrub:
        block: 31
        data: 0
        chance: 0.8
      cactus:
        block: 81
        data: 0
        chance: 0.2
    treeCount: 0
    treeTypes: null
    schematicCount: 0
    schematics: null
    veinCount: 15
    veinTypes:
      diamond:
        block: 56
        data: 0
        chance: 0.01
        length: 2
        stroke: 1
      gold:
        block: 14
        data: 0
        chance: 0.04
        length: 2
        stroke: 2
      iron:
        block: 15
        data: 0
        chance: 0.12
        length: 3
        stroke: 2
      coal:
        block: 16
        data: 0
        chance: 0.17
        length: 3
        stroke: 3
      redstone:
        block: 73
        data: 0
        chance: 0.05
        length: 3
        stroke: 2
      granite:
        block: 1
        data: 1
        chance: 0.05
        length: 3
        stroke: 2
      diorite:
        block: 1
        data: 3
        chance: 0.05
        length: 3
        stroke: 2
      andesite:
        block: 1
        data: 5
        chance: 0.05
        length: 3
        stroke: 2
      air:
        block: 0
        data: 0
        chance: 0.3
        length: 10
        stroke: 4
  plains:
    r: 200
    g: 255
    b: 0
    blocks:
      GRASS:
        block: 2
        data: 0
        chance: 0.9
      COARSEDIRT:
        block: 3
        data: 1
        chance: 0.1
    biome: PLAINS
    snow: false
    floraCount: 120
    floraTypes:
      grass:
        block: 31
        data: 1
        chance: 0.9
      farn:
        block: 31
        data: 2
        chance: 0.1
      yellow:
        block: 37
        data: 0
        chance: 0.05
      red:
        block: 38
        data: 0
        chance: 0.05
      white:
        block: 38
        data: 3
        chance: 0.1
    treeCount: 0
    treeTypes: null
    schematicCount: 0
    schematics: null
    veinCount: 15
    veinTypes:
      diamond:
        block: 56
        data: 0
        chance: 0.01
        length: 2
        stroke: 1
      gold:
        block: 14
        data: 0
        chance: 0.04
        length: 2
        stroke: 2
      iron:
        block: 15
        data: 0
        chance: 0.12
        length: 3
        stroke: 2
      coal:
        block: 16
        data: 0
        chance: 0.17
        length: 3
        stroke: 3
      redstone:
        block: 73
        data: 0
        chance: 0.05
        length: 3
        stroke: 2
      granite:
        block: 1
        data: 1
        chance: 0.05
        length: 3
        stroke: 2
      diorite:
        block: 1
        data: 3
        chance: 0.05
        length: 3
        stroke: 2
      andesite:
        block: 1
        data: 5
        chance: 0.05
        length: 3
        stroke: 2
      air:
        block: 0
        data: 0
        chance: 0.3
        length: 10
        stroke: 4
  ocean:
    r: 0
    g: 0
    b: 255
    blocks:
      SAND:
        block: 12
        data: 0
        chance: 0.3
      DIRT:
        block: 3
        data: 0
        chance: 0.3
      GRAVEL:
        block: 13
        data: 0
        chance: 0.3
      CLAY:
        block: 82
        data: 0
        chance: 0.1
    biome: OCEAN
    snow: false
    floraCount: 0
    floraTypes: null
    treeCount: 0
    treeTypes: null
    schematicCount: 0
    schematics: null
    veinCount: 12
    veinTypes:
      diamond:
        block: 56
        data: 0
        chance: 0.02
        length: 2
        stroke: 1
      gold:
        block: 14
        data: 0
        chance: 0.05
        length: 2
        stroke: 2
      iron:
        block: 15
        data: 0
        chance: 0.1
        length: 3
        stroke: 2
      coal:
        block: 16
        data: 0
        chance: 0.15
        length: 3
        stroke: 3
      redstone:
        block: 73
        data: 0
        chance: 0.04
        length: 3
        stroke: 2
      granite:
        block: 1
        data: 1
        chance: 0.05
        length: 3
        stroke: 2
      diorite:
        block: 1
        data: 3
        chance: 0.05
        length: 3
        stroke: 2
      andesite:
        block: 1
        data: 5
        chance: 0.05
        length: 3
        stroke: 2
      air:
        block: 0
        data: 0
        chance: 0.5
        length: 14
        stroke: 5
  taiga:
    r: 0
    g: 50
    b: 0
    blocks:
      DIRT:
        block: 3
        data: 0
        chance: 0.2
      COARSEDIRT:
        block: 3
        data: 1
        chance: 0.2
      PODSOL:
        block: 3
        data: 2
        chance: 0.25
      GRAVEL:
        block: 13
        data: 0
        chance: 0.1
      GRASS:
        block: 2
        data: 0
        chance: 0.4
      STONE:
        block: 1
        data: 0
        chance: 0.1
    biome: TAIGA_COLD
    snow: true
    floraCount: 25
    floraTypes:
      grass:
        block: 31
        data: 1
        chance: 0.4
      farn:
        block: 31
        data: 2
        chance: 0.4
    treeCount: 12
    treeTypes:
      redwood:
        type: REDWOOD
        chance: 0.9
      megaredwood:
        type: MEGA_REDWOOD
        chance: 0.1
      tallredwood:
        type: TALL_REDWOOD
        chance: 0.1
    schematicCount: 0
    schematics: null
    veinCount: 12
    veinTypes:
      diamond:
        block: 56
        data: 0
        chance: 0.01
        length: 2
        stroke: 1
      gold:
        block: 14
        data: 0
        chance: 0.07
        length: 2
        stroke: 2
      iron:
        block: 15
        data: 0
        chance: 0.2
        length: 3
        stroke: 2
      coal:
        block: 16
        data: 0
        chance: 0.25
        length: 3
        stroke: 3
      redstone:
        block: 73
        data: 0
        chance: 0.01
        length: 3
        stroke: 2
      granite:
        block: 1
        data: 1
        chance: 0.1
        length: 3
        stroke: 2
      diorite:
        block: 1
        data: 3
        chance: 0.1
        length: 3
        stroke: 2
      andesite:
        block: 1
        data: 5
        chance: 0.1
        length: 3
        stroke: 2
      air:
        block: 0
        data: 0
        chance: 0.3
        length: 10
        stroke: 3