name: BitmapGenerator
version: '${minecraft.plugin.version}'
main: io.github.apfelcreme.BitmapGenerator.BitmapGeneratorPlugin
author: Lord36
load: STARTUP
api-version: "1.15"
commands:
  bitmapgenerator:
    aliases: [bmpgen]
    permission: bitmapgenerator.command
    usage: /<command> reload